### ISSUE TITLE
doesn't work on an interactive shell

### ISSUE THREAD

**Issue by vlussenburg** [backtrace-labs/backtrace-python#9]
Tested on Python2/Python3 on MacOs
https://xxxxxxxxxxx.sp.backtrace.io/p/xxxxxxxx/settings/integration-guides?doc=python

Error:
```
Vincents-MacBook-Pro-7:petportal vincentlussenburg$ python3
Python 3.7.3 (default, Mar 27 2019, 09:23:32) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import backtracepython as bt
>>> 
>>> bt.initialize(
...   endpoint="https://submit.backtrace.io/testing-jknkjnnl/abshsdbfjsdhfbsdjfbsjdhf/json",
...   token="abshsdbfjsdhfbsdjfbsjdhf"
... )
>>> try:
...     data = open("foo.txt").read()
... except:
...     bt.send_last_exception()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'foo.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.7/site-packages/backtracepython/__init__.py", line 249, in send_last_exception
    report = BacktraceReport()
  File "/usr/local/lib/python3.7/site-packages/backtracepython/__init__.py", line 112, in __init__
    entry_path = os.path.abspath(__main__.__file__)
AttributeError: module '__main__' has no attribute '__file__'
```

DOES WORK when put into a python file directly

**Comment by konraddysput** [comment]
it should be fixed in this pull request: https://github.com/backtrace-labs/backtrace-python/pull/13
